apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-minikube-ingress
spec:
  rules:
    - host: devops-gitops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-nonprod.local
                port:
                  number: 80
