name: CI - Build & Push Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and run lint
        working-directory: app
        run: |
          npm ci || npm install
          npm run lint
    
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/mohamedhamdy120/devops-pipeline-app
          TAG=${{ github.sha }}

          docker build -f app/Dockerfile -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest app
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/mohamedhamdy120/devops-pipeline-app:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/mohamedhamdy120/devops-pipeline-app
          TAG=${{ github.sha }}

          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
