name: CD - Promote to Prod

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to promote (e.g. a commit SHA)"
        required: true

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PUSH_TOKEN }}

      - name: Update GitOps prod image tag
        run: |
          sed -i "s|image: ghcr.io/mohamedhamdy120/devops-pipeline-app:.*|image: ghcr.io/mohamedhamdy120/devops-pipeline-app:${{ inputs.image_tag }}|" gitops/prod/deployment.yaml

      - name: Commit & push GitOps change (prod)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gitops/prod/deployment.yaml
          git commit -m "Promote prod to ${{ inputs.image_tag }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.CI_PUSH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
